### ISSUE TITLE
Getting two similar waveform 

### ISSUE THREAD

**Issue by anilsharmanp** [fm140905/CoMPASSBin2CSV#1]
Hello, 

I am working for our own lab caen's digitizer and trying to check the .bin data files and .csv files as well. I am getting two same waveforms at different timestamps. what do you think about that? I have checked your coincidence test data files from your coincidence repository but that .bin file contains different waveforms for different timestamps. I am attaching my .csv file for reference.

Thanks:)
[DataR_CH6@DT5725_1621_run_31.CSV](https://github.com/fm140905/CoMPASSBin2CSV/files/12646335/DataR_CH6%40DT5725_1621_run_31.CSV)

**Comment by fm140905** [comment]
Hi @Hachiman512 sorry for my late reply. I was sick for the past few days. The data in your CSV seems fine to me. I plotted the first 100 pulses and did not see anything suspicious. See picture below.
![image](https://github.com/fm140905/CoMPASSBin2CSV/assets/45578549/fa583b2a-7094-44ab-b37b-36f5060704c9)

The pulse height spectrum also looks fine. 
![image](https://github.com/fm140905/CoMPASSBin2CSV/assets/45578549/e83df3a6-4ff5-493c-9ae0-4913bf466b15)

So I think your data is good. As for the two same waveforms you mentioned, I think it's just some random coincidence.

```python
## code to produce these two plots
from matplotlib import pyplot as plt
import numpy as np


class Pulse:
    def __init__(self, strs):
        self.board_num = -int(strs[0])
        self.channel_num = int(strs[1])
        self.time_stamp_ps = int(strs[2])
        self.waveform = np.array([int(s) for s in strs[6:]])


if __name__ == "__main__":
    pulses = []
    with open("DataR_CH6@DT5725_1621_run_31.CSV", 'r') as f:
        next(f)
        for line in f:
            substrs = line.strip().split(',')
            pulses.append(Pulse(substrs))
    print(len(pulses))
    fig, ax = plt.subplots(figsize=(6,6))
    for i in range(100):
        ax.plot(np.arange(len(pulses[0].waveform)), pulses[i].waveform)
    plt.show()

    baselines = np.array([np.mean(pulses[i].waveform[:8]) for i in range(len(pulses))])
    heights = np.array([np.min(pulses[i].waveform) for i in range(len(pulses))])
    heights = baselines - heights
    plt.hist(heights, bins=300)
    plt.show()

```

**Comment by anilsharmanp** [comment]
That's really helpful. thanks for that!
